### ISSUE TITLE
Problem with block number

### ISSUE THREAD

**Issue by sullof** [TRON-US/trongrid#2]
Refer to this https://github.com/TRON-US/tronweb/issues/27

**Comment by redshround** [comment]
I have a problem. When I run tron-cli quick and tron-cli init to synchronize the main network, I need to download the gridapi package at https://github.com/tronprotocol/tron-grid.git-branch: dev. But when I downloaded it, he suggested that there is no such file. Now I found https://github.com/tronprotocol/tron-grid.git-branch: dev has been updated to https://github.com/tron-us /trongrid.git-branch: dev is on, what should I do? , modify the URL in the constants which is more appropriate
![image](https://user-images.githubusercontent.com/38822519/61692113-9da75b80-ad5f-11e9-9884-35e1e0750f9d.png)

**Comment by sullof** [comment]
That is a problem in tron-cli.
